const mongoose = require('mongoose');

// اتصال به دیتابیس
mongoose.connect('mongodb://localhost/admin', { useNewUrlParser: true, useUnifiedTopology: true });

// مدل ایستگاه آتش‌نشانی (FireStation)
const stationSchema = new mongoose.Schema({
    name: String,
    firereport: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Report' }],
    firerighter: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Firefighter' }],
    operations: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Operation' }] ,
    stationID: { type: String, required: true, unique: true },
    stationName: { type: String, required: true },
    stationAddress: { type: String, required: true },
    establishmentDate: { type: Date, required: true },
    stationChief: { type: String, required: true },
    stationPhoneNumber: { type: String, required: true },
    stationEmail: { type: String, required: true },
    stationStatus: { type: String, required: true },
    geographicalCoordinates: {
        latitude: { type: Number, required: true },
        longitude: { type: Number, required: true }
    },
    coverageArea: { type: String, required: true },
    accessToHighways: { type: String, required: true },
    availableEquipment: [String],
    numberOfVehicles: { type: Number, required: true },
    equipmentMaintenanceStatus: { type: String, required: true },
    dormitoryFacilities: { type: String, required: true },
    communicationCoverage: { type: String, required: true },
    numberOfFirefighters: { type: Number, required: true },
    workShifts: [String],
    personnelList: [String],
    trainingCourses: [String],
    numberOfOperations: { type: Number, required: true },
    responseTimeToIncidents: { type: String, required: true },
    stationPerformance: { type: String, required: true },
    damageAndCasualties: { type: String, required: true },
    stationBudget: { type: Number, required: true },
    insuranceAndLegalSupport: { type: String, required: true },
    culturalAndSocialActivities: [String],
    retrainingPrograms: [String]
});

const FireStation = mongoose.model('Station', stationSchema);

// تابع برای اضافه کردن ایستگاه‌ها به دیتابیس
const createFireStations = async () => {
    try {
        const fireStationsData = [
            {
                stationID: 'S0011',
                stationName: 'ایستگاه آتش‌نشانی ۱',
                stationAddress: 'تهران، میدان حسن‌آباد، ضلع شمال غربی',
                establishmentDate: new Date('1980-01-01'),
                stationChief: 'محمد احمدی',
                stationPhoneNumber: '۰۲۱۶۶۷۰۱۱۲۷',
                stationEmail: 'station1@example.com',
                stationStatus: 'فعال',
                geographicalCoordinates: { latitude: 35.6895, longitude: 51.3890 },
                coverageArea: 'میدان حسن‌آباد و اطراف',
                accessToHighways: 'نزدیکی به بزرگراه‌های اصلی',
                availableEquipment: ['دستگاه تنفسی', 'آتش‌نشانی'],
                numberOfVehicles: 5,
                equipmentMaintenanceStatus: 'در حال تعمیر',
                dormitoryFacilities: '۵ خوابگاه',
                communicationCoverage: 'رادیو و تلفن',
                numberOfFirefighters: 20,
                workShifts: ['صبح', 'عصر', 'شب'],
                personnelList: ['علی احمدی', 'مریم موسوی'],
                trainingCourses: ['دوره امداد و نجات', 'دوره اطفای حریق'],
                numberOfOperations: 200,
                responseTimeToIncidents: '۵ دقیقه',
                stationPerformance: 'بسیار عالی',
                damageAndCasualties: '۵ نفر زخمی',
                stationBudget: 50000000,
                insuranceAndLegalSupport: 'بیمه تامین اجتماعی',
                culturalAndSocialActivities: ['ورزش', 'آموزش خانوادگی'],
                retrainingPrograms: ['دوره‌های بازآموزی']
            },
            {
                stationID: 'S0021',
                stationName: 'ایستگاه آتش‌نشانی ۲',
                stationAddress: 'تهران، خیابان انقلاب، مقابل دانشگاه تهران',
                establishmentDate: new Date('1982-05-15'),
                stationChief: 'علی رضایی',
                stationPhoneNumber: '۰۲۱۶۶۷۳۲۴۵۶',
                stationEmail: 'station2@example.com',
                stationStatus: 'فعال',
                geographicalCoordinates: { latitude: 35.7020, longitude: 51.3580 },
                coverageArea: 'خیابان انقلاب و اطراف',
                accessToHighways: 'نزدیکی به بزرگراه‌های امام علی و حقانی',
                availableEquipment: ['دستگاه تنفسی', 'آتش‌نشانی'],
                numberOfVehicles: 4,
                equipmentMaintenanceStatus: 'در حال تعمیر',
                dormitoryFacilities: '۴ خوابگاه',
                communicationCoverage: 'رادیو و اینترنت',
                numberOfFirefighters: 18,
                workShifts: ['صبح', 'عصر', 'شب'],
                personnelList: ['مرتضی نیکو', 'سپیده معصومی'],
                trainingCourses: ['دوره امداد و نجات', 'دوره پیشرفته'],
                numberOfOperations: 150,
                responseTimeToIncidents: '۶ دقیقه',
                stationPerformance: 'خوب',
                damageAndCasualties: '۳ نفر زخمی',
                stationBudget: 40000000,
                insuranceAndLegalSupport: 'بیمه سلامت',
                culturalAndSocialActivities: ['آموزش خانواده‌ها', 'ورزش'],
                retrainingPrograms: ['دوره‌های بازآموزی']
            },
            {
                stationID: 'S0013',
                stationName: 'ایستگاه آتش‌نشانی ۳',
                stationAddress: 'تهران، منطقه ۲۲، بلوار پژوهش',
                establishmentDate: new Date('1990-07-23'),
                stationChief: 'سید احمد موسوی',
                stationPhoneNumber: '۰۲۱۶۶۷۸۹۹۲۳',
                stationEmail: 'station3@example.com',
                stationStatus: 'فعال',
                geographicalCoordinates: { latitude: 35.7575, longitude: 51.3498 },
                coverageArea: 'منطقه ۲۲ و اطراف',
                accessToHighways: 'نزدیکی به بزرگراه‌های شهید چمران و حکیم',
                availableEquipment: ['دستگاه تنفسی', 'آتش‌نشانی', 'ماشین نجات'],
                numberOfVehicles: 6,
                equipmentMaintenanceStatus: 'در حال استفاده',
                dormitoryFacilities: '۶ خوابگاه',
                communicationCoverage: 'رادیو و تلفن',
                numberOfFirefighters: 25,
                workShifts: ['صبح', 'عصر', 'شب'],
                personnelList: ['حسن جعفری', 'فاطمه حسین‌زاده'],
                trainingCourses: ['دوره تخصصی اطفای حریق'],
                numberOfOperations: 180,
                responseTimeToIncidents: '۷ دقیقه',
                stationPerformance: 'متوسط',
                damageAndCasualties: '۴ نفر زخمی',
                stationBudget: 55000000,
                insuranceAndLegalSupport: 'بیمه کارگری',
                culturalAndSocialActivities: ['ورزش'],
                retrainingPrograms: ['دوره‌های تخصصی']
            },
            {
                stationID: 'S0104',
                stationName: 'ایستگاه آتش‌نشانی ۴',
                stationAddress: 'تهران، شهرک غرب، بلوار شهید باهنر',
                establishmentDate: new Date('1995-08-10'),
                stationChief: 'حسین طاهری',
                stationPhoneNumber: '۰۲۱۶۶۷۲۳۴۵۶',
                stationEmail: 'station4@example.com',
                stationStatus: 'فعال',
                geographicalCoordinates: { latitude: 35.7605, longitude: 51.3585 },
                coverageArea: 'شهرک غرب و اطراف',
                accessToHighways: 'نزدیکی به بزرگراه‌های شهید همت و شهید یادگار امام',
                availableEquipment: ['دستگاه تنفسی', 'آتش‌نشانی', 'دوربین حرارتی'],
                numberOfVehicles: 4,
                equipmentMaintenanceStatus: 'در حال استفاده',
                dormitoryFacilities: '۴ خوابگاه',
                communicationCoverage: 'رادیو و تلفن همراه',
                numberOfFirefighters: 22,
                workShifts: ['صبح', 'عصر', 'شب'],
                personnelList: ['علی اکبری', 'فاطمه عبداللهی'],
                trainingCourses: ['دوره‌های پیشرفته'],
                numberOfOperations: 210,
                responseTimeToIncidents: '۶ دقیقه',
                stationPerformance: 'عالی',
                damageAndCasualties: '۲ نفر زخمی',
                stationBudget: 60000000,
                insuranceAndLegalSupport: 'بیمه مسولیت',
                culturalAndSocialActivities: ['ورزش', 'آموزش ایمنی'],
                retrainingPrograms: ['دوره‌های بازآموزی']
            },
            {
                stationID: 'S0015',
                stationName: 'ایستگاه آتش‌نشانی ۵',
                stationAddress: 'تهران، شمال تهران، خیابان ولیعصر',
                establishmentDate: new Date('2000-01-01'),
                stationChief: 'محمد حسین‌پور',
                stationPhoneNumber: '۰۲۱۶۶۷۵۲۳۴۵',
                stationEmail: 'station5@example.com',
                stationStatus: 'فعال',
                geographicalCoordinates: { latitude: 35.7880, longitude: 51.3850 },
                coverageArea: 'شمال تهران و اطراف',
                accessToHighways: 'نزدیکی به بزرگراه‌های صدر و نیایش',
                availableEquipment: ['دستگاه تنفسی', 'آتش‌نشانی', 'بالابر'],
                numberOfVehicles: 7,
                equipmentMaintenanceStatus: 'در حال استفاده',
                dormitoryFacilities: '۷ خوابگاه',
                communicationCoverage: 'رادیو و تلفن همراه',
                numberOfFirefighters: 30,
                workShifts: ['صبح', 'عصر', 'شب'],
                personnelList: ['مهدی شریفی', 'سحر موسوی'],
                trainingCourses: ['دوره‌های تخصصی'],
                numberOfOperations: 250,
                responseTimeToIncidents: '۴ دقیقه',
                stationPerformance: 'بسیار عالی',
                damageAndCasualties: '۶ نفر زخمی',
                stationBudget: 70000000,
                insuranceAndLegalSupport: 'بیمه تامین اجتماعی',
                culturalAndSocialActivities: ['ورزش', 'برگزاری کلاس‌های آموزشی'],
                retrainingPrograms: ['دوره‌های بازآموزی']
            },
            {
                stationID: 'S006',
                stationName: 'ایستگاه آتش‌نشانی ۶',
                stationAddress: 'تهران، شرق تهران، میدان آزادی',
                establishmentDate: new Date('2005-06-17'),
                stationChief: 'صادق عبدالهی',
                stationPhoneNumber: '۰۲۱۶۶۷۴۵۶۷۸',
                stationEmail: 'station6@example.com',
                stationStatus: 'فعال',
                geographicalCoordinates: { latitude: 35.6930, longitude: 51.3900 },
                coverageArea: 'میدان آزادی و اطراف',
                accessToHighways: 'نزدیکی به بزرگراه‌های شهید فهمیده و جلال آل احمد',
                availableEquipment: ['دستگاه تنفسی', 'آتش‌نشانی'],
                numberOfVehicles: 5,
                equipmentMaintenanceStatus: 'در حال تعمیر',
                dormitoryFacilities: '۵ خوابگاه',
                communicationCoverage: 'رادیو و تلفن',
                numberOfFirefighters: 25,
                workShifts: ['صبح', 'عصر', 'شب'],
                personnelList: ['علی رحیمی', 'زهره رضایی'],
                trainingCourses: ['دوره امداد و نجات', 'دوره اطفای حریق'],
                numberOfOperations: 220,
                responseTimeToIncidents: '۸ دقیقه',
                stationPerformance: 'متوسط',
                damageAndCasualties: '۳ نفر زخمی',
                stationBudget: 60000000,
                insuranceAndLegalSupport: 'بیمه کارگری',
                culturalAndSocialActivities: ['ورزش', 'آموزش ایمنی'],
                retrainingPrograms: ['دوره‌های بازآموزی']
            },
            {
                stationID: 'S007',
                stationName: 'ایستگاه آتش‌نشانی ۷',
                stationAddress: 'تهران، غرب تهران، خیابان طالقانی',
                establishmentDate: new Date('2010-09-29'),
                stationChief: 'مسعود فرزاد',
                stationPhoneNumber: '۰۲۱۶۶۷۵۵۴۴۴',
                stationEmail: 'station7@example.com',
                stationStatus: 'فعال',
                geographicalCoordinates: { latitude: 35.7570, longitude: 51.4110 },
                coverageArea: 'غرب تهران و اطراف',
                accessToHighways: 'نزدیکی به بزرگراه‌های آیت‌الله کاشانی و حکیم',
                availableEquipment: ['دستگاه تنفسی', 'آتش‌نشانی', 'دوربین حرارتی'],
                numberOfVehicles: 6,
                equipmentMaintenanceStatus: 'در حال استفاده',
                dormitoryFacilities: '۶ خوابگاه',
                communicationCoverage: 'رادیو و اینترنت',
                numberOfFirefighters: 27,
                workShifts: ['صبح', 'عصر', 'شب'],
                personnelList: ['بابک نظری', 'یاسمن قاسمی'],
                trainingCourses: ['دوره امداد و نجات'],
                numberOfOperations: 240,
                responseTimeToIncidents: '۷ دقیقه',
                stationPerformance: 'عالی',
                damageAndCasualties: '۲ نفر زخمی',
                stationBudget: 75000000,
                insuranceAndLegalSupport: 'بیمه تامین اجتماعی',
                culturalAndSocialActivities: ['ورزش'],
                retrainingPrograms: ['دوره‌های بازآموزی']
            },
            {
                stationID: 'S008',
                stationName: 'ایستگاه آتش‌نشانی ۸',
                stationAddress: 'تهران، مرکز تهران، خیابان ولیعصر',
                establishmentDate: new Date('2015-11-13'),
                stationChief: 'کیومرث احسانی',
                stationPhoneNumber: '۰۲۱۶۶۷۶۶۷۸۹',
                stationEmail: 'station8@example.com',
                stationStatus: 'فعال',
                geographicalCoordinates: { latitude: 35.7540, longitude: 51.4270 },
                coverageArea: 'مرکز تهران و اطراف',
                accessToHighways: 'نزدیکی به بزرگراه‌های شهید چمران و ولیعصر',
                availableEquipment: ['دستگاه تنفسی', 'آتش‌نشانی'],
                numberOfVehicles: 5,
                equipmentMaintenanceStatus: 'در حال تعمیر',
                dormitoryFacilities: '۵ خوابگاه',
                communicationCoverage: 'رادیو و تلفن همراه',
                numberOfFirefighters: 24,
                workShifts: ['صبح', 'عصر', 'شب'],
                personnelList: ['سینا صالحی', 'مریم اخباری'],
                trainingCourses: ['دوره‌های تخصصی'],
                numberOfOperations: 270,
                responseTimeToIncidents: '۶ دقیقه',
                stationPerformance: 'خوب',
                damageAndCasualties: '۳ نفر زخمی',
                stationBudget: 80000000,
                insuranceAndLegalSupport: 'بیمه مسولیت',
                culturalAndSocialActivities: ['آموزش ایمنی'],
                retrainingPrograms: ['دوره‌های بازآموزی']
            },
            {
                stationID: 'S009',
                stationName: 'ایستگاه آتش‌نشانی ۹',
                stationAddress: 'تهران، منطقه ۱، خیابان میرداماد',
                establishmentDate: new Date('2020-02-20'),
                stationChief: 'کامران لواسانی',
                stationPhoneNumber: '۰۲۱۶۶۷۹۹۷۶۵',
                stationEmail: 'station9@example.com',
                stationStatus: 'فعال',
                geographicalCoordinates: { latitude: 35.7680, longitude: 51.4320 },
                coverageArea: 'منطقه ۱ تهران و اطراف',
                accessToHighways: 'نزدیکی به بزرگراه‌های شهید چمران و نیایش',
                availableEquipment: ['دستگاه تنفسی', 'آتش‌نشانی'],
                numberOfVehicles: 6,
                equipmentMaintenanceStatus: 'در حال استفاده',
                dormitoryFacilities: '۶ خوابگاه',
                communicationCoverage: 'رادیو و تلفن همراه',
                numberOfFirefighters: 29,
                workShifts: ['صبح', 'عصر', 'شب'],
                personnelList: ['حسین حسینی', 'الناز رحیمی'],
                trainingCourses: ['دوره امداد و نجات'],
                numberOfOperations: 300,
                responseTimeToIncidents: '۵ دقیقه',
                stationPerformance: 'عالی',
                damageAndCasualties: '۲ نفر زخمی',
                stationBudget: 90000000,
                insuranceAndLegalSupport: 'بیمه کارگری',
                culturalAndSocialActivities: ['ورزش', 'آموزش ایمنی'],
                retrainingPrograms: ['دوره‌های تخصصی']
            },
            {
                stationID: 'S010',
                stationName: 'ایستگاه آتش‌نشانی ۱۰',
                stationAddress: 'تهران، جنوب تهران، میدان بهارستان',
                establishmentDate: new Date('2022-05-10'),
                stationChief: 'سجاد برزگر',
                stationPhoneNumber: '۰۲۱۶۶۷۸۲۳۴۶',
                stationEmail: 'station10@example.com',
                stationStatus: 'فعال',
                geographicalCoordinates: { latitude: 35.6892, longitude: 51.3718 },
                coverageArea: 'میدان بهارستان و اطراف',
                accessToHighways: 'نزدیکی به بزرگراه‌های شهید عباسپور و امام خمینی',
                availableEquipment: ['دستگاه تنفسی', 'آتش‌نشانی'],
                numberOfVehicles: 4,
                equipmentMaintenanceStatus: 'در حال تعمیر',
                dormitoryFacilities: '۴ خوابگاه',
                communicationCoverage: 'رادیو و تلفن همراه',
                numberOfFirefighters: 18,
                workShifts: ['صبح', 'عصر', 'شب'],
                personnelList: ['مرتضی فرشاد', 'محسن عباسی'],
                trainingCourses: ['دوره‌های پیشرفته'],
                numberOfOperations: 350,
                responseTimeToIncidents: '۸ دقیقه',
                stationPerformance: 'خوب',
                damageAndCasualties: '۴ نفر زخمی',
                stationBudget: 100000000,
                insuranceAndLegalSupport: 'بیمه تامین اجتماعی',
                culturalAndSocialActivities: ['آموزش ایمنی'],
                retrainingPrograms: ['دوره‌های تخصصی']
            },
            {
                stationID: 'S011',
                stationName: 'ایستگاه آتش‌نشانی ۱۱',
                stationAddress: 'تهران، شرق تهران، میدان آزادی',
                establishmentDate: new Date('2023-02-14'),
                stationChief: 'امیر علی‌زاده',
                stationPhoneNumber: '۰۲۱۶۶۷۷۹۷۶۵',
                stationEmail: 'station11@example.com',
                stationStatus: 'فعال',
                geographicalCoordinates: { latitude: 35.7070, longitude: 51.4290 },
                coverageArea: 'منطقه شرق تهران و اطراف',
                accessToHighways: 'نزدیکی به بزرگراه‌های بابایی و شهید دستغیب',
                availableEquipment: ['دستگاه تنفسی', 'آتش‌نشانی'],
                numberOfVehicles: 4,
                equipmentMaintenanceStatus: 'در حال استفاده',
                dormitoryFacilities: '۴ خوابگاه',
                communicationCoverage: 'رادیو و تلفن',
                numberOfFirefighters: 15,
                workShifts: ['صبح', 'عصر', 'شب'],
                personnelList: ['فرید جعفری', 'نگین باقری'],
                trainingCourses: ['دوره‌های امداد و نجات'],
                numberOfOperations: 400,
                responseTimeToIncidents: '۶ دقیقه',
                stationPerformance: 'متوسط',
                damageAndCasualties: '۳ نفر زخمی',
                stationBudget: 110000000,
                insuranceAndLegalSupport: 'بیمه تامین اجتماعی',
                culturalAndSocialActivities: ['ورزش'],
                retrainingPrograms: ['دوره‌های تخصصی']
            }
        ];

        await FireStation.insertMany(fireStationsData);
        console.log('✅ ۱۱ ایستگاه آتش‌نشانی با موفقیت اضافه شدند.');
    } catch (error) {
        console.error('❌ خطا در اضافه کردن ایستگاه‌ها:', error);
    }
};

// اجرای تابع برای ایجاد ایستگاه‌ها
createFireStations();
