const mongoose = require('mongoose');

// مدل Firefighter
const firefighterSchema = new mongoose.Schema({
  personalPhoto: String,
  employeeNumber: String,
  hireDate: Date,
  firstName: String,
  lastName: String,
  fatherName: String,
  idNumber: String,
  nationalId: String,
  employmentType: String,
  birthPlace: String,
  birthDate: Date,
  maritalStatus: String,
  numberOfChildren: Number,
  jobGroup: { type: Number, min: 7, max: 30 },
  jobPosition: String,
  organizationalPost: String,
  educationLevel: String,
  major: String,
  insuranceNumber: String,
  insuranceType: String,
  eyeColor: String,
  height: Number,
  weight: Number,
  skinColor: String,
  training: [String],
  religion: String,
  sect: String,
  retirementStatus: String,
  gender: String,
  bloodGroup: String,
  address: String,
  contactNumber: String,
  email: { type: String, unique: true },
  city: String,
  country: String,
  district: String,
  additionalInfo: String,
  stations: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Station' }],
  shifts: [String],
  endDate: Date,
  trainingDocuments: [String],
  firefighterSpecialtyCourses: [String],
  certificates: [String],
  skillsAndAbilities: [String],
  medicalHistory: [String],
  publicPerformanceEvaluations: [String],
  bossPerformanceEvaluations: [String],
  crisisZoneTravels: [String],
  internationalMissions: [String],
  successfulAndFailedOperations: [String],
  salary: Number,
}, { timestamps: true });

const Firefighter = mongoose.model('Firefighter', firefighterSchema);


module.exports = Firefighter;
